name: Deploy Image
run-name: ${{ github.actor }} is deploying the stats-dash
on: workflow_call
jobs:
  deploy-image:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - uses: actions/checkout@v4
      - run: cat deployment.yaml
      - name: Inject Variables
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '["**/*deployment.yaml"]'
        env:
          APP_IMAGE: europeana/statistics-dashboard:${{ github.event.inputs.tag_name || secrets.PROJECT_VERSION }}
      - run: ls -l
      - run: cat deployment.yaml
      - uses: actions/checkout@v4

      #- name: replace app settings
      #  run: |
      #    rm appsettings.json
      #    mv appsettings_tokenized.json appsettings.json
