name: Deploy Image
run-name: ${{ github.actor }} is deploying the stats-dash
on:
  workflow_call:
    inputs:
      deploy_environment:
        description: 'Target Environment'
        required: true
        type: string
        #default: 'test'
        #type: choice
        #options:
        #- test
        #- acceptance
        #- production
      docker_image_name:
        description: 'Docker image (url)'
        type: string
        required: true

jobs:
  log-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'Input check'
          echo ${ inputs.deploy_environment }
          echo ${ inputs.docker_image_name }
