name: Deploy Image
run-name: ${{ github.actor }} is deploying the stats-dash
on:
  workflow_call:
    inputs:
      deploy_environment:
        description: 'Environment to deploy to'
        required: true
        default: 'test'
        type: string
      #docker_image_name:
      #  description: 'Docker image (url)'
      #  type: string
      #  required: true

jobs:
  log-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'Input check'
          echo ${ github.event.inputs.deploy_environment }
      #echo ${ inputs.docker_image_name }
