name: Deploy Image
run-name: ${{ github.actor }} is deploying the stats-dash
on:
  workflow_call:
    inputs:
      deploy_environment:
        description: 'Environment to deploy to'
        required: true
        default: 'test'
        type: string
      docker_image_name:
        description: 'Docker image (url)'
        type: string
        required: true

jobs:
  deploy-image:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: |
          echo 'Input check'
          echo ${{ inputs.deploy_environment }}
          echo ${{ inputs.docker_image_name }}

      - run: cat deployment.yml

      #- uses: actions/checkout@v3
      #- name: Inject Variables
      #    uses: lindluni/actions-variable-groups@v2
      #    with:
            #groups: |
            #.github/variables/dev.yml
      #      groups: |
      #        deployment.yaml

      - uses: cschleiden/replace-tokens@v1
          with:
            tokenPrefix: '#{'
            tokenSuffix: '}#'
            files: '["**/*_tokenized.yaml"]'

      - run: cat deployment_tokenized.yml

      #- name: replace app settings
      #  run: |
      #    rm appsettings.json
      #    mv appsettings_tokenized.json appsettings.json
