name: Deploy Image
run-name: ${{ github.actor }} is deploying the stats-dash
on:
  workflow_call:
    inputs:
      deploy_environment:
        description: 'Environment to deploy to'
        required: true
        default: 'test'
        type: string
      docker_image_name:
        description: 'Docker image (url)'
        type: string
        required: true

jobs:
  deploy-image:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - uses: actions/checkout@v4
      - run: |
          echo 'Input check'
          echo ${{ inputs.deploy_environment }}
          echo ${{ inputs.docker_image_name }}

      - run: cat deployment.yaml
      - name: Inject Variables
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '["**/*_tokenized.yaml"]'

      - run: ls -l

      #- name: replace app settings
      #  run: |
      #    rm appsettings.json
      #    mv appsettings_tokenized.json appsettings.json
