name: Deploy Image
run-name: ${{ github.actor }} is deploying the stats-dash
on: workflow_call
jobs:
  deploy-image:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - uses: actions/checkout@v4
      - run: cat deployment/${{ github.event.inputs.deploy_environment }}/deployment.yaml
      - run: cat deployment/${{ github.event.inputs.deploy_environment }}/hpa.yaml
      - name: Inject Variables
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '["deployment/${{ github.event.inputs.deploy_environment }}/*.yaml"]'
        env:
          APP_IMAGE: europeana/statistics-dashboard:${{ github.event.inputs.tag_name || secrets.PROJECT_VERSION }}
          MAX_REPLICAS: '4'
          MIN_REPLICAS: '2'
          UTILISATION_AVERAGE_PERCENT: '75'
      - run: ls -l
      - run: cat deployment/${{ github.event.inputs.deploy_environment }}/deployment.yaml
      - run: cat deployment/${{ github.event.inputs.deploy_environment }}/hpa.yaml
      - uses: actions/checkout@v4

      #- name: replace app settings
      #  run: |
      #    rm appsettings.json
      #    mv appsettings_tokenized.json appsettings.json
