name: Build & Test Stats Dashboard
run-name: ${{ github.actor }} is building / testing the stats-dash
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: europeana/statistics-dashboard
      - uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'
      - run: npm install
      - run: npm run test:dev
      - run: cp coverage/**/lcov.info .
      - uses: actions/upload-artifact@master
        with:
          name: appSource
          path: src/app
      - uses: actions/upload-artifact@master
        with:
          name: appLcov
          path: ./lcov.info
  run-sonar:
    needs: 'run-tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/download-artifact@master
        with:
          name: appSource
          path: src/app
      - uses: actions/download-artifact@master
        with:
          name: appLcov
          path: ./lcov.info
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ls -l
