name: Build & Test Stats Dashboard
run-name: ${{ github.actor }} is building / testing the stats-dash
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: europeana/statistics-dashboard
      - uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'
      - run: npm install
      - run: npm run test:dev
      - run: cp coverage/**/lcov.info .
      - uses: actions/upload-artifact@master
        with:
          name: appSource
          path: src/app
      - uses: actions/upload-artifact@master
        with:
          name: appLcov
          path: .
  run-sonar:
    needs: 'run-tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: appSource
          path: src/app
      - uses: actions/download-artifact@master
        with:
          name: appLcov
          path: .
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=europeana
            -Dsonar.projectKey=europeana_statistics-dashboard
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.sources=src/app
            -Dsonar.exclusions=src/**/_mocked/**
            -Dsonar.javascript.lcov.reportPaths=./lcov.info
