name: '- helper (testing)'
on:
  workflow_call:
    outputs:
      pass_unit:
        description: "Good enough?"
        value: ${{ jobs['run-unit-tests'].outputs.result }}

jobs:
  run-cypress:
    if: ${{ github.event.inputs.run_build == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: europeana/statistics-dashboard
          ref: ${{ github.event.inputs.tag_name }}
      - uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'
      - run: npm install
      - name: Run Cypress Tests
        run: |
          ((npm run start:ci-data & echo 'started test-data server')
          && sleep 15) & (npm run cypress:run)
      - name: close test-data server
        if: success() || failure()
        run: |
          fuser -k 3001/tcp
      - name: close test-data server
        if: success() || failure()
        run: fuser -k 3001/tcp,

  run-accessibility-tests:
    if: ${{ github.event.inputs.run_build == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: europeana/statistics-dashboard
          ref: ${{ github.event.inputs.tag_name }}
      - uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'
      - run: npm install

      - name: Run Cypress Tests
        run: |
          ((npm run start:ci-data & echo 'started test-data server')
          && sleep 15) & (npm run cypress:ci-accessibility)

      - name: close test-data server
        if: success() || failure()
        run: |
          fuser -k 3001/tcp

  run-unit-tests:
    if: ${{ github.event.inputs.run_build == 'true' }}
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      result: ${{ steps['run-unit-tests-step'].outputs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: europeana/statistics-dashboard
          ref: ${{ github.event.inputs.tag_name }}
      - uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'
      - run: npm install
      - id: run-unit-tests-step
        run: npm run test:dev >> $GITHUB_OUTPUT
      - run: cp coverage/**/lcov.info .
      - uses: actions/upload-artifact@master
        with:
          name: appSource
          path: src/app
      - uses: actions/upload-artifact@master
        with:
          name: appLcov
          path: ./lcov.info
