name: '- helper (e2e testing)'
on:
  workflow_call:
    outputs:
      qa_pass:
        value: ${{ jobs['cypress'].outputs.qa_pass }}
jobs:
  cypress:
    if: ${{ github.event.inputs.run_build == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      qa_pass: ${{ steps['execute'].outputs.qa_pass }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: europeana/statistics-dashboard
          ref: ${{ github.event.inputs.tag_name }}
      - uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'
      - run: npm install


      - name: Run Cypress Tests
        id: execute
        run: |
          (npm run start:ci-data) & (sleep 10 && npm run cypress:ci)
          echo qa_pass=$? >> $GITHUB_OUTPUT

      - name: close test-data server
        if: success() || failure()
        run: |
          fuser -k 3001/tcp

  a11y:
    if: ${{ github.event.inputs.run_build == 'true' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: europeana/statistics-dashboard
          ref: ${{ github.event.inputs.tag_name }}

      - uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'

      - run: npm install

      - name: Run Cypress AccessibilityTests
        run: |
          ((npm run start:ci-data & echo 'started test-data server')
          && sleep 10) & (npm run cypress:ci-accessibility)


      - name: close test-data server
        if: success() || failure()
        run: |
          fuser -k 3001/tcp
